# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-17 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Current_Openings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=250)),
                ('Experience', models.CharField(max_length=250)),
                ('Job_Description', models.CharField(max_length=10000)),
                ('Roles_and_Responsibilities', models.CharField(max_length=10000)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
