# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=250)),
                ('Name', models.CharField(max_length=200)),
                ('Experience', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Mobile', models.PositiveIntegerField()),
                ('Resume', models.FileField(upload_to='Resumes/')),
                ('Feedback', models.CharField(max_length=10000)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
