# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='Resumes/'),
        ),
    ]
