# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-18 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_auto_20181018_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='Resume',
            field=models.FileField(upload_to='Resumes/'),
        ),
    ]
