# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NationalNewsChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('channel_url', models.URLField()),
                ('channel_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='NewsChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('National', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.NationalNewsChannels')),
            ],
        ),
        migrations.CreateModel(
            name='RegionalNewsChannels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('channel_url', models.URLField()),
                ('channel_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='newschannels',
            name='Regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.RegionalNewsChannels'),
        ),
    ]
