# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-09 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Main_Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PublisherDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Add_Logo', models.FileField(blank=True, null=True, upload_to='publisher_details/')),
                ('Type', models.CharField(choices=[('1', 'Paper'), ('2', 'Magazine')], max_length=100)),
                ('Main_Edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.Main_Edition')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='States/')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Edition', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Title',
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspaper',
            name='Uploaded_at',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newspaper',
            name='mainedition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='subedition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newspaper',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publisherdetail',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.State'),
        ),
        migrations.AddField(
            model_name='publisherdetail',
            name='Sub_Edition',
            field=models.ManyToManyField(to='contents.Edition'),
        ),
        migrations.AddField(
            model_name='publisherdetail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='main_edition',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.State'),
        ),
        migrations.AddField(
            model_name='edition',
            name='State',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.State'),
        ),
    ]
