# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebooks_name', models.CharField(max_length=100)),
                ('ebooks_url', models.URLField()),
                ('ebooks_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magazine_name', models.CharField(max_length=100)),
                ('magazine_url', models.URLField()),
                ('magazine_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='NationalNewsChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('channel_url', models.URLField()),
                ('channel_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='NationalNewsPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newspaper_name', models.CharField(max_length=100)),
                ('newspaper_url', models.URLField()),
                ('newspaper_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='NewsChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('National', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.NationalNewsChannel')),
            ],
        ),
        migrations.CreateModel(
            name='RegionalNewsChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=100)),
                ('channel_url', models.URLField()),
                ('channel_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RegionalNewsPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newspaper_name', models.CharField(max_length=100)),
                ('newspaper_url', models.URLField()),
                ('newspaper_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SocialChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialchannels_name', models.CharField(max_length=100)),
                ('socialchannels_url', models.URLField()),
                ('socialchannels_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='newschannels',
            name='National',
        ),
        migrations.RemoveField(
            model_name='newschannels',
            name='Regional',
        ),
        migrations.DeleteModel(
            name='NationalNewsChannels',
        ),
        migrations.DeleteModel(
            name='NewsChannels',
        ),
        migrations.DeleteModel(
            name='RegionalNewsChannels',
        ),
        migrations.AddField(
            model_name='newschannel',
            name='Regional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.RegionalNewsChannel'),
        ),
    ]
