# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-14 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20180813_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='ebooks_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='ebook',
            old_name='ebooks_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ebook',
            old_name='ebooks_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='magazine',
            old_name='magazine_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='magazine',
            old_name='magazine_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='magazine',
            old_name='magazine_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='nationalnewschannel',
            old_name='channel_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='nationalnewschannel',
            old_name='channel_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='nationalnewschannel',
            old_name='channel_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='nationalnewspaper',
            old_name='newspaper_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='nationalnewspaper',
            old_name='newspaper_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='nationalnewspaper',
            old_name='newspaper_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='regionalnewschannel',
            old_name='channel_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='regionalnewschannel',
            old_name='channel_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='regionalnewschannel',
            old_name='channel_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='regionalnewspaper',
            old_name='newspaper_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='regionalnewspaper',
            old_name='newspaper_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='regionalnewspaper',
            old_name='newspaper_url',
            new_name='url',
        ),
        migrations.RenameField(
            model_name='socialchannel',
            old_name='socialchannels_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='socialchannel',
            old_name='socialchannels_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='socialchannel',
            old_name='socialchannels_url',
            new_name='url',
        ),
    ]
