# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_articlereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalforum',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='politicalforum',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='politicalforum',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
