# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20180918_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalforum',
            name='video_link',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
