# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_politicalforum_video_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticianArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='Politician_Articles/')),
                ('Description', models.CharField(max_length=10000)),
                ('Month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.Month')),
            ],
        ),
    ]
