# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-18 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_month_politicianarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article_upload',
            name='Author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='article_upload',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
