# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_auto_20180918_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Poll_Question', models.CharField(max_length=1000)),
                ('Upvote', models.PositiveIntegerField()),
                ('DownVote', models.PositiveIntegerField()),
                ('Month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.Month')),
            ],
        ),
    ]
