# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_newspaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
