# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_polling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling',
            name='DownVote',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='polling',
            name='Upvote',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
