# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_auto_20180818_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='magazine',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
