# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-19 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_auto_20180919_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polling',
            name='DownVote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='polling',
            name='Upvote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
