# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Poll_Question', models.CharField(max_length=1000)),
            ],
        ),
    ]
