# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_auto_20180920_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polling',
            name='Poll_Question',
        ),
    ]
