# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0015_remove_polling_poll_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalsurvey',
            name='DownVote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='politicalsurvey',
            name='Month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contents.Month'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='politicalsurvey',
            name='Upvote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
