# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0016_auto_20180920_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicianarticle',
            name='Title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
