# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-21 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0017_politicianarticle_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='Uploaded_at',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='magazine',
            name='user',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
