# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-23 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0019_auto_20180921_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherdetail',
            name='Add_Logo',
            field=models.FileField(blank=True, null=True, upload_to='publisher_details/', verbose_name='image'),
        ),
    ]
