# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-24 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0020_auto_20180923_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalforum',
            name='Position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.PoliticalPosition'),
        ),
    ]
