# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0021_auto_20180924_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('web_link', models.URLField()),
                ('android_link', models.URLField()),
                ('ios_link', models.URLField()),
            ],
        ),
    ]
