# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0023_auto_20180925_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newschannel',
            name='image',
            field=models.ImageField(upload_to='NewsChannel_Logos'),
        ),
    ]
