# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0024_auto_20180925_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Ebook_images/')),
                ('intro', models.ImageField(upload_to='Ebook_intros/')),
                ('pdf', models.FileField(upload_to='Ebooks/')),
            ],
        ),
    ]
