# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0025_ebookupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebookupload',
            name='intro',
        ),
    ]
