# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0027_ebookupload_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('Poll_Question', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='articlereview',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='articlereview',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='articlereview',
            name='vote_score',
        ),
    ]
