# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0029_newspaperapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalforum',
            name='Polling',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
