# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0032_auto_20181008_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalCommentSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('user', models.CharField(max_length=100)),
                ('uploaded_on', models.DateField(auto_now=True)),
                ('comment_title', models.CharField(max_length=256)),
                ('comment', models.CharField(max_length=20000)),
                ('ratings', models.CharField(choices=[('1', 'BAD'), ('2', 'AVERAGE'), ('3', 'GOOD'), ('4', 'VERY GOOD'), ('5', 'EXCELLENT')], max_length=100)),
            ],
        ),
    ]
