# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0035_auto_20181012_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherDetailEdition',
            fields=[
                ('edition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contents.Edition')),
                ('Name1', models.CharField(max_length=100)),
            ],
            bases=('contents.edition', models.Model),
        ),
    ]
