from django.contrib import admin
from .forms import ArticleForm
from .models import (NationalNewsChannel,RegionalNewsChannel,Magazine,SocialChannel,Ebook,RegionalNewsPaper,NationalNewsPaper,Article,Edition,
NewsPaper,State,PublisherDetail,Main_Edition,Sub_Edition,PoliticalForum,Dummy,Article_upload,Revenue,ArticleReview,Month,PoliticianArticle,Polling,
Vote,PoliticalSurvey)

admin.site.register(RegionalNewsChannel)
admin.site.register(NationalNewsChannel)
admin.site.register(Magazine)
admin.site.register(SocialChannel)
admin.site.register(Ebook)
admin.site.register(RegionalNewsPaper)
admin.site.register(NationalNewsPaper)
admin.site.register(Article)
admin.site.register(NewsPaper)
admin.site.register(Edition)
admin.site.register(State)
admin.site.register(PublisherDetail)
admin.site.register(Main_Edition)
admin.site.register(Sub_Edition)
admin.site.register(PoliticalForum)
admin.site.register(Dummy)
admin.site.register(Article_upload)
admin.site.register(Revenue)
admin.site.register(ArticleReview)
admin.site.register(Month)
admin.site.register(PoliticianArticle)
admin.site.register(Polling)
admin.site.register(Vote)
admin.site.register(PoliticalSurvey)