# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-14 17:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magazines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publishing_House', models.CharField(max_length=100)),
                ('Magazine_Name', models.CharField(max_length=100)),
                ('Add_Thumbnail', models.FileField(upload_to='Magazine_Thumbnails/')),
                ('Add_Magazine', models.FileField(upload_to='Magazines/')),
                ('Language', models.CharField(max_length=100)),
                ('Category', models.CharField(choices=[('1', 'Entertainment'), ('2', 'Sports'), ('3', 'Health'), ('4', 'Business')], max_length=100)),
                ('Periodicity', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=100)),
                ('Place', models.CharField(max_length=400)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publishing_House', models.CharField(max_length=100)),
                ('Publishing_Name', models.CharField(max_length=100)),
                ('Add_PDF', models.FileField(null=True, upload_to='NewsPapers/')),
                ('Add_Logo', models.FileField(null=True, upload_to='Logos/')),
                ('Number_of_Editions', models.PositiveIntegerField()),
                ('Main_Edition', models.CharField(blank=True, max_length=100, null=True)),
                ('Sub_Edition', models.CharField(max_length=100)),
                ('Languages', models.CharField(max_length=100)),
                ('Periodicity', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Daily', max_length=100)),
                ('Uploading_By', models.CharField(choices=[('Single_File', 'Single_File'), ('Page_by_Page', 'Page_by_Page'), ('Edition', 'Edition'), ('Api_code', 'Api_code')], default='Single_File', max_length=100)),
                ('Type', models.CharField(choices=[('1', 'National'), ('2', 'Regional')], default='National', max_length=100)),
                ('State', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.State')),
                ('Sub_Editions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contents.Sub_Edition')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('Account_type', models.CharField(choices=[('1', 'Publisher'), ('2', 'Customer'), ('3', 'Advertiser'), ('4', 'Politician')], max_length=100)),
                ('Company_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('Lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
                ('Application_type', models.CharField(choices=[('1', 'Android'), ('2', 'IOS')], max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
