# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 14:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Publishing_House', models.CharField(max_length=100)),
                ('Publishing_Name', models.CharField(max_length=100)),
                ('Add_Logo', models.FileField(upload_to='media/')),
                ('Number_of_Editions', models.PositiveIntegerField()),
                ('Sub_Editions', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=400)),
                ('Languages', models.CharField(max_length=100)),
                ('Periodicity', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Daily', max_length=100)),
                ('Uploading_By', models.CharField(choices=[('Single_File', 'Single_File'), ('Page_by_Page', 'Page_by_Page'), ('Edition', 'Edition'), ('Api_code', 'Api_code')], default='Single_File', max_length=100)),
                ('Uploader_Contact_Details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('Account_type', models.CharField(choices=[('1', 'Publisher'), ('2', 'Customer'), ('3', 'Advertiser')], max_length=100)),
                ('Company_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
