# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180808_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
