# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180910_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Add_PDF',
            field=models.FileField(null=True, upload_to='NewsPapers/'),
        ),
    ]
