# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
