# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181009_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Mobile_Num',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
