# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180910_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Add_PDF',
            field=models.FileField(null=True, upload_to='NewsPapers/'),
        ),
    ]
