# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-17 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Uploader_Contact_Details',
            new_name='user',
        ),
    ]
