# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-09 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_social_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Lastname',
        ),
    ]
