# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180817_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Add_Logo',
            new_name='Add_PDF',
        ),
        migrations.AddField(
            model_name='post',
            name='Type',
            field=models.CharField(choices=[('1', 'National'), ('2', 'Regional')], default='National', max_length=100),
        ),
    ]
