# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-18 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180818_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Add_PDF',
            field=models.FileField(upload_to='NewsPapers/'),
        ),
    ]
