# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180818_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Application_Type',
            field=models.CharField(choices=[('1', 'Android'), ('2', 'IOS')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
