# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20180819_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password1',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='password2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
