# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-19 19:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180819_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Password1',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Password2',
            new_name='password2',
        ),
    ]
