# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180827_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Application_type',
            field=models.CharField(choices=[('1', 'Android'), ('2', 'IOS')], default='Android', max_length=100, null=True),
        ),
    ]
