# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20180827_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Add_Logo',
            field=models.FileField(null=True, upload_to='Logos/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Add_PDF',
            field=models.FileField(null=True, upload_to='NewsPapers/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
