# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contents', '0035_auto_20181012_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Page_Num', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=100)),
                ('Date', models.DateField()),
                ('Duration', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=200)),
                ('Edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.Edition')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.NewsPaper')),
            ],
        ),
    ]
