# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createad',
            name='Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contents.PublisherDetail'),
        ),
    ]
