# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_auto_20181023_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createad',
            name='Edition',
            field=models.CharField(max_length=250),
        ),
    ]
