# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0035_auto_20181012_1131'),
        ('advertisement', '0004_auto_20181023_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='createad',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Edition', to='contents.PublisherDetail'),
            preserve_default=False,
        ),
    ]
