# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_createad_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createad',
            name='Edition',
        ),
    ]
