# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0009_auto_20181023_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createad',
            name='Duration',
            field=models.PositiveIntegerField(),
        ),
    ]
