# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0010_auto_20181023_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=222)),
                ('Banner_Link', models.URLField(blank=True, null=True)),
                ('Banner_Image', models.ImageField(upload_to='Advertisements/')),
                ('user', models.CharField(max_length=220)),
            ],
        ),
    ]
