# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-23 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0011_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='status',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
