# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=10000)),
                ('image', models.ImageField(upload_to='NewsFeeds/')),
                ('category', models.CharField(choices=[('1', 'Headlines/Breaking News'), ('2', 'Educational'), ('3', 'Entertainment'), ('4', 'Business'), ('5', 'Sports'), ('6', 'LifeStyle'), ('7', 'Social'), ('8', 'World/International'), ('9', 'Global')], max_length=100)),
                ('created_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
